package com.mateuszroszkowski.FindAmiGo.model;

public enum SportName {
    FOOTBALL, BASKETBALL, TENNIS, RUNNING, VOLLEYBALL, SWIMMING, TABLETENNIS, DANCING, GYMNASTICS, ARCHERY, MARTIALARTS,
    BADMINTON, SKATEBOARDING, ICESKATING, SNOWSPORTS, FRISBEE, CLIMBING, HIKING, CYCLING, POOL, HORSERIDING,
    FISHING, GOLF, HANDBALL, HUNTING, TRIATHLON, SAILING, SHOOTINGSPORTS, ICEHOCKEY, PARKOUR, WEIGHTLIFTING, GYM,
    SQUASH, KAYAKING, DIVING, MOTORIZEDSPORTS, PAINTBALL, DARTS, CHESS, CARDGAMES, ESPORTS, SPEEDCUBING, BOARDGAMES,
    ATHLETICS, BOWLING, OTHER, ALL
}
